package builder

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"domain-list-manager/internal/domain"
	"domain-list-manager/internal/fetcher"
	"domain-list-manager/internal/parser"
	"domain-list-manager/internal/source"
)

type Builder struct {
	fetcher     *fetcher.Fetcher
	sourceRepo  source.Repository
	domainRepo  domain.Repository
	outputPath  string
}

type BuildResult struct {
	Domains      []string
	TotalSources int
	TotalFetched int
	TotalParsed  int
	TotalDomains int
	Duplicates   int
	Errors       []string
	BuildTime    time.Duration
}

type BuilderConfig struct {
	Timeout    time.Duration
	MaxRetries int
	OutputPath string
}

func NewBuilder(sourceRepo source.Repository, domainRepo domain.Repository, cfg BuilderConfig) *Builder {
	f := fetcher.New(
		fetcher.WithTimeout(cfg.Timeout),
		fetcher.WithMaxRetries(cfg.MaxRetries),
	)
	return &Builder{
		fetcher:    f,
		sourceRepo: sourceRepo,
		domainRepo: domainRepo,
		outputPath: cfg.OutputPath,
	}
}

func (b *Builder) Build() (*BuildResult, error) {
	start := time.Now()

	sources, err := b.sourceRepo.List()
	if err != nil {
		return nil, fmt.Errorf("list sources: %w", err)
	}

	var allDomains []string
	seen := make(map[string]bool)
	totalSources := 0
	totalFetched := 0
	totalParsed := 0
	var errors []string

	autoParser := parser.NewAutoParser()

	for _, src := range sources {
		if !src.Enabled {
			continue
		}
		totalSources++

		result, err := b.processSource(src, autoParser, seen)
		if err != nil {
			errors = append(errors, fmt.Sprintf("%s: %v", src.Name, err))
			src.LastError = err.Error()
			if uerr := b.sourceRepo.Update(src.ID, src); uerr != nil {
				errors = append(errors, fmt.Sprintf("update source %s: %v", src.Name, uerr))
			}
			continue
		}

		if result == nil {
			continue
		}

		totalFetched++
		totalParsed += result.Parsed
		allDomains = append(allDomains, result.Domains...)
	}

	normalized := make([]string, 0, len(seen))
	duplicates := len(allDomains) - len(seen)

	for d := range seen {
		normalized = append(normalized, d)
	}

	if b.domainRepo != nil {
		manualDomains, err := b.domainRepo.ListBySource("manual")
		if err == nil {
			for _, d := range manualDomains {
				domain := strings.ToLower(strings.TrimSpace(d.Name))
				if domain == "" || seen[domain] {
					continue
				}
				seen[domain] = true
				normalized = append(normalized, domain)
			}
		}
	}

	sort.Strings(normalized)

	result := &BuildResult{
		Domains:      normalized,
		TotalSources: totalSources,
		TotalFetched: totalFetched,
		TotalParsed:  totalParsed,
		TotalDomains: len(normalized),
		Duplicates:   duplicates,
		Errors:       errors,
		BuildTime:    time.Since(start),
	}

	return result, nil
}

type sourceProcessResult struct {
	Domains []string
	Parsed  int
}

func (b *Builder) processSource(src *source.Source, autoParser *parser.AutoParser, seen map[string]bool) (*sourceProcessResult, error) {
	content, err := b.fetchSource(src)
	if err != nil {
		return nil, fmt.Errorf("fetch: %w", err)
	}

	if content == nil {
		return nil, nil
	}

	entries, err := autoParser.Parse(content)
	if err != nil {
		return nil, fmt.Errorf("parse: %w", err)
	}

	var newDomains []string
	for _, e := range entries {
		domain := strings.ToLower(strings.TrimSpace(e.Domain))
		if domain == "" {
			continue
		}

		if seen[domain] {
			continue
		}
		seen[domain] = true
		newDomains = append(newDomains, domain)
	}

	src.LastError = ""
	src.LastUpdate = time.Now().UTC()
	src.DomainCount = len(entries)
	if uerr := b.sourceRepo.Update(src.ID, src); uerr != nil {
		return nil, fmt.Errorf("update source: %w", uerr)
	}

	return &sourceProcessResult{
		Domains: newDomains,
		Parsed:  len(entries),
	}, nil
}

func (b *Builder) fetchSource(src *source.Source) ([]byte, error) {
	resp, err := b.fetcher.Fetch(src.URL, "", "")
	if err != nil {
		return nil, err
	}

	return resp.Body, nil
}

func (b *Builder) WriteOutput(result *BuildResult) error {

	dir := b.outputPath
	lastSlash := strings.LastIndex(dir, "/")
	lastBackslash := strings.LastIndex(dir, "\\")
	dirEnd := lastSlash
	if lastBackslash > lastSlash {
		dirEnd = lastBackslash
	}
	if dirEnd > 0 {
		if err := os.MkdirAll(dir[:dirEnd], 0755); err != nil {
			return fmt.Errorf("create output dir: %w", err)
		}
	}

	f, err := os.Create(b.outputPath)
	if err != nil {
		return fmt.Errorf("create output file: %w", err)
	}
	defer f.Close()

	fmt.Fprintln(f, "# Generated by DomainListManager")
	fmt.Fprintf(f, "# Build time: %s\n", time.Now().UTC().Format("2006-01-02 15:04:05"))
	fmt.Fprintf(f, "# Total domains: %d\n", result.TotalDomains)
	fmt.Fprintf(f, "# Sources fetched: %d/%d\n", result.TotalFetched, result.TotalSources)
	fmt.Fprintf(f, "# Duplicates removed: %d\n", result.Duplicates)
	fmt.Fprintln(f, "")

	for _, d := range result.Domains {
		fmt.Fprintln(f, d)
	}

	return nil
}

func (b *Builder) OutputPath() string {
	return b.outputPath
}
